export const header = [
    {
        title: <span className="Table_tittle">Action</span>,
    },
    {
        title: (
            <span
                className="Table_tittle"
                style={{
                    marginLeft: "10px",
                }}
            >
                Notes
            </span>
        ),
    },
    {
        title: <span className="Table_tittle">Risk</span>,
    },
];
export const title = (
    <>
        <br />
        <span className="Tittle">Human</span>
    </>
);
export const title1 = (
    <>
        <br />
        <span className="Tittle">Implant</span>{" "}
    </>
);
export const title2 = (
    <>
        <br />
        <span className="Tittle">Cyborg</span>{" "}
    </>
);
export const title3 = (
    <>
        <br />
        <span className="Tittle">Minting</span>
    </>
);

export const data = [
    {
        name: <span>Enter city (stake)</span>,
        notes: (
            <div className="Notes">
                Accumulate 10,000
                <span style={{ color: "#02ffff" }}> $NEON </span> / day
                (prorated to the second)
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
    {
        name: <span>Collect $NEON (harvest)</span>,
        notes: (
            <div className="Notes">
                Receive 80% of <span style={{ color: "#02ffff" }}> $NEON </span>
                accumulated on your Human
                <br />
            </div>
        ),
        risk: (
            <div
                style={{
                    maxWidth: "200px",
                    fontSize: "12px",
                }}
            >
                Implants take a guaranteed 20% tax on collected $NEON in return
                for not attacking the Human if there is no Cyborg in your team.
                Taxed $NEON is split among all the Implants currently staked in
                the city.
            </div>
        ),
    },
    {
        name: <span>Leave City (unstake)</span>,
        notes: (
            <div className="Notes">
                Human is removed from the City and all
                <span style={{ color: "#02ffff" }}> $NEON </span> is collected.
                Can only be done if the Human has accumulated 3 days worth of
                <span style={{ color: "#02ffff" }}> $NEON </span>
                to keep it warm
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
];
export const data1 = [
    {
        name: <span>Stake Ipmlant</span>,
        notes: (
            <div className="Notes">
                Earn your share of the 20% tax of all{" "}
                <span style={{ color: "#02ffff" }}> $NEON </span> generated by
                Human in the City
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
    {
        name: <span>Claim $NEON</span>,
        notes: (
            <div className="Notes">
                Stake Implant Earn your share of the taxes of all Receive all
                <span style={{ color: "#02ffff" }}> $NEON </span> taxes accrued
                for the staked Implant
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
    {
        name: <span>Unstake Implant</span>,
        notes: (
            <div className="Notes">
                Receive all <span style={{ color: "#02ffff" }}> $NEON </span>
                taxes accrued for the staked Implant
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
    {
        name: <span>Use 'Hack' ability</span>,
        notes: (
            <div className="Notes">
                There is a 10% Steals 30% of unclaimed accumulated
                <span style={{ color: "#02ffff" }}> $NEON </span> balance from
                random user
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
];
export const data2 = [
    {
        name: <span>Stake Cyborg</span>,
        notes: (
            <div className="Notes">
                Accumulate 10,000
                <span style={{ color: "#02ffff" }}> $NEON </span> / day
                (prorated to the second), enchances "Hack" ability so it steal
                50% instead of 30%. Exempt Humans from 20% taxes
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
    {
        name: <span>Claim $NEON</span>,
        notes: (
            <div className="Notes">
                Receive all <span style={{ color: "#02ffff" }}> $NEON </span>
                taxes accrued for the staked Implant
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
    {
        name: <span>Unstake Cyborg</span>,
        notes: (
            <div className="Notes">
                Receive all <span style={{ color: "#02ffff" }}> $NEON </span>
                taxes accrued for the staked Implant
                <br />
            </div>
        ),
        risk: <b>No risk</b>,
    },
];
export const data3 = [
    {
        name: <span>Mint a new resident using $NEON</span>,
        notes: (
            <div className="Notes">
                There is a 10% chance that the NFT is actually a Cyborg and 30%
                chance it is an Implant!
                <br />
            </div>
        ),
        risk: (
            <div
                style={{
                    maxWidth: "200px",
                    fontSize: "12px",
                }}
            >
                15% chance of the new Human, Implant or even Cyborg being stolen
                by a staked Implant.
            </div>
        ),
    },
];
